language: node_js
cache:
  apt: true
  directories:
    - node_modules
node_js:
#  - "0.10"
  - "0.12"
  - iojs
before_install:
  - curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/preinstall.sh | sudo bash -
  - sudo apt-get update -y
  - sudo apt-get install -y graphicsmagick imagemagick ffmpeg
install:
  - npm install
after_success:
  - bash ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/piobyte/flamingo.git
  - secure: "JMdtUr8MWYN0mhWiwivcWGhGXUOJnOv5UGSfsurYsGVKyqK0qRJMVmf+bezMkIhxktcq6RJNAmYq/1wsh1mqU/iHoWaAHeOtZoMYItYgIco6GJgfYJ2Dhb46WiRbDzi5qcEjCV3fDb3K8OXePWVcBoGAvp5e+pH3vvvw0SgAjBY="
