language: node_js
cache:
  yarn: true
  apt: true
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- sudo apt-get -y install pkg-config
- sudo bash tools/install-ffmpeg.sh
- sudo bash tools/install-imagemagick.sh
- sudo bash tools/install-graphicsmagick.sh
- ls -la test/fixtures/images

stages:
- test
- benchmark

jobs:
  include:
  - stage: test
    node_js: 'lts/boron'
    script: yarn run test
  - stage: test
    node_js: 'lts/carbon'
    script: yarn run test
  - stage: test
    node_js: 'node'
    script: yarn run test && yarn formats
  - stage: benchmark
    node_js: 'lts/carbon'
    script: yarn run bench
  - stage: benchmark
    node_js: 'node'
    script: yarn run bench
