language: node_js
cache:
  apt: true
  directories:
    - node_modules
node_js:
  - "0.10"
  - "0.12"
  - iojs
before_install:
  - curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/preinstall.sh | sudo bash -
  - sudo apt-get update -y
  - sudo apt-get install -y graphicsmagick imagemagick ffmpeg
install:
  - npm install
